// nuxt-js/app/components/site/LanguageToggle.vue
<script setup lang="ts">
// EN/ES language switcher — the v4 white segmented pill (design D6). Under
// Polylang each language is a real URL (English at "/", Spanish at "/es/…"), so
// each segment is an <a> linking to the current page's translation (Polylang
// falls back to the language home when the page has no translation). The active
// language is a brand-blue filled segment marked aria-current; navigating is the
// entire behavior — no cookie, no machine translation. data-native-nav forces a
// full page load: switching language must re-render the whole page server-side.
// The header island lives outside #main and stays mounted across client swaps,
// so its `languages` URLs are refreshed per-navigation via the reactive
// lib/languages store (see ts/navigation.ts + SiteHeader.vue) — otherwise each
// segment's href would freeze at the entry page's translation.
export interface LanguageLink {
  code: string;
  label: string;
  name: string;
  active: boolean;
  url: string;
}

withDefaults(
  defineProps<{
    /** One entry per site language, from the server (see inc/i18n.php). */
    languages?: LanguageLink[];
    /** Group height: desktop 42px · tablet / mobile panel 44px (touch target). */
    size?: "desktop" | "tablet" | "mobile";
  }>(),
  {
    languages: () => [],
    size: "desktop",
  },
);

const HEIGHT = {
  desktop: "h-[42px]",
  tablet: "h-11",
  mobile: "h-11",
} as const;

// v4 segment: Bowlby One 0.8rem, tracked, radius 999; brand fill when active.
// Segments stretch to the group's full height (≥ 44px on touch tiers) and the
// active fill keeps the canvas' 3px white inset via a white border.
const segmentClass =
  "box-border inline-flex cursor-pointer items-center self-stretch rounded-full border-[3px] px-[13px] font-display text-[0.8rem] leading-none font-normal tracking-[0.04em] no-underline hover:underline hover:underline-offset-[3px]";
</script>

<template>
  <div
    v-if="languages.length > 1"
    role="group"
    aria-label="Language"
    :class="[
      'notranslate box-border flex items-center gap-0.5 overflow-hidden rounded-full bg-white px-1',
      HEIGHT[size],
    ]"
  >
    <a
      v-for="lang in languages"
      :key="lang.code"
      :href="lang.url"
      data-native-nav
      :lang="lang.code"
      :title="lang.name"
      :aria-current="lang.active ? 'true' : undefined"
      :class="[
        segmentClass,
        lang.active ? 'border-white bg-brand text-white' : 'border-transparent bg-transparent text-brand',
      ]"
    >
      {{ lang.label }}
    </a>
  </div>
</template>

// next-js/components/site/LanguageToggle.tsx
import type { LanguageLink } from "@/lib/contracts";
import { resolveHref } from "@/lib/links";
import { cn } from "@/lib/utils";

/* EN/ES switcher — the v4 white segmented pill (design D6). Each segment links
 * to the current page's translation (Polylang falls back to the language home).
 * A plain <a>: switching language is a full document load on purpose, so
 * <html lang>, the chrome and every string re-render for the new language. */
const HEIGHT = { desktop: "h-[42px]", tablet: "h-11", mobile: "h-11" } as const;
const SEGMENT =
  "box-border inline-flex cursor-pointer items-center self-stretch rounded-full border-[3px] px-[13px] font-display text-[0.8rem] leading-none font-normal tracking-[0.04em] no-underline hover:underline hover:underline-offset-[3px]";

export function LanguageToggle({
  languages = [],
  size = "desktop",
  wpOrigin,
  label = "Language",
}: {
  languages?: LanguageLink[];
  size?: keyof typeof HEIGHT;
  wpOrigin: string;
  label?: string;
}) {
  if (languages.length < 2) return null;
  return (
    <div
      role="group"
      aria-label={label}
      className={cn(
        "notranslate box-border flex items-center gap-0.5 overflow-hidden rounded-full bg-white px-1",
        HEIGHT[size],
      )}
    >
      {languages.map((l) => {
        const href = resolveHref(l.url, wpOrigin);
        return (
          <a
            key={l.code}
            href={href.href}
            data-native-nav=""
            lang={l.code}
            title={l.name}
            aria-current={l.active ? "true" : undefined}
            className={cn(
              SEGMENT,
              l.active
                ? "border-white bg-brand text-white"
                : "border-transparent bg-transparent text-brand",
            )}
          >
            {l.label}
          </a>
        );
      })}
    </div>
  );
}
