// nuxt-js/app/components/site/SingleEvent.vue
<script setup lang="ts">
/* Single event island (openspec progress-now-v4-events D4, specs "Event hero"
 * … "More upcoming events"). Hero = PageHeader with extras (white date tile +
 * translucent-ink category pill before the h1; when/where lede; RSVP +
 * Add-to-calendar pills). Content = "About this event" + event blocks on the
 * v4 tokens; sticky sidebar = LinkListCard rows (Date / Time / Location) +
 * CtaCard "Save your spot" (omitted without an RSVP link); "More upcoming
 * events" = EventCard rows on the alt band. views/single-event.twig mirrors
 * the crawlable shell with the same class recipes. */
import { computed } from "vue";
import ImageSlot from "@/components/site/blog/ImageSlot.vue";
import CtaCard from "@/components/site/CtaCard.vue";
import DashedNote from "@/components/site/DashedNote.vue";
import EventBlocks from "@/components/site/EventBlocks.vue";
import EventCard from "@/components/site/EventCard.vue";
import LinkListCard from "@/components/site/LinkListCard.vue";
import PageHeader from "@/components/site/PageHeader.vue";
import {
  categoryById,
  type EventCategory,
  MONTH_NAMES,
  MONTH_SHORTS,
  parseISODate,
  type RelatedEvent,
  setCategories,
  type SingleEventData,
} from "@/lib/events";

const props = withDefaults(
  defineProps<{
    event: SingleEventData;
    /** WP term-driven categories — replaces the registry palette when provided */
    categories?: EventCategory[];
    related?: RelatedEvent[];
    showRelated?: boolean;
    homeUrl?: string;
    calendarUrl?: string;
    /** translated UI strings */
    crumbHome?: string;
    crumbCalendar?: string;
    rsvpLabel?: string;
    addToCalendarLabel?: string;
    aboutLabel?: string;
    detailsLabel?: string;
    dateLabel?: string;
    timeLabel?: string;
    locationLabel?: string;
    saveTitle?: string;
    saveBody?: string;
    saveLabel?: string;
    contactLabel?: string;
    moreLabel?: string;
    fullCalendarLabel?: string;
    viewLabel?: string;
  }>(),
  {
    categories: undefined,
    related: () => [],
    showRelated: true,
    homeUrl: "/",
    calendarUrl: "/calendar/",
    crumbHome: "Home",
    crumbCalendar: "Calendar",
    rsvpLabel: "RSVP",
    addToCalendarLabel: "Add to calendar",
    aboutLabel: "About this event",
    detailsLabel: "Details",
    dateLabel: "Date",
    timeLabel: "Time",
    locationLabel: "Location",
    saveTitle: "Save your spot",
    saveBody: "RSVP and we’ll send the details straight to you.",
    saveLabel: "RSVP Now",
    contactLabel: "Questions? Contact",
    moreLabel: "More upcoming events",
    fullCalendarLabel: "Full calendar",
    viewLabel: "View event",
  },
);

if (props.categories && props.categories.length > 0) setCategories(props.categories);

const WEEKDAYS_LONG = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

const category = computed(() => categoryById(props.event.cat));
const date = computed(() => parseISODate(props.event.date));
const dayNum = computed(() => String(date.value.getDate()).padStart(2, "0"));
const monthShort = computed(() => MONTH_SHORTS[date.value.getMonth()]!.toUpperCase());
/** "Tuesday, September 8, 2026" */
const longDate = computed(
  () => `${WEEKDAYS_LONG[date.value.getDay()]}, ${MONTH_NAMES[date.value.getMonth()]} ${date.value.getDate()}, ${date.value.getFullYear()}`,
);

const isOnline = computed(() => props.event.locationType === "online");
const locationLine = computed(() => {
  if (isOnline.value) return "Online · link shared on RSVP";
  const place = [props.event.venue, props.event.city].filter(Boolean).join(" · ");
  if (props.event.locationType === "hybrid") return place ? `${place} · or online` : "In person or online";
  return place || "Location TBA";
});
/** hero lede: "<weekday, date> · <time> · <location>" */
const whenWhere = computed(() =>
  [longDate.value, props.event.time, locationLine.value].filter(Boolean).join(" · "),
);

const detailRows = computed(() => {
  const rows = [
    { label: props.dateLabel, value: longDate.value },
    ...(props.event.time ? [{ label: props.timeLabel, value: props.event.doorsTime ? `${props.event.time} · doors ${props.event.doorsTime}` : props.event.time }] : []),
    { label: props.locationLabel, value: locationLine.value },
  ];
  return rows;
});

const hasContact = computed(
  () => props.event.contact.name !== "" || props.event.contact.email !== "" || props.event.contact.phone !== "",
);
const hasImage = computed(() => Boolean(props.event.featuredImage.src));
const hasBody = computed(() => hasImage.value || props.event.summary !== "" || props.event.blocks.length > 0);
const moreEvents = computed(() => (props.showRelated ? props.related.slice(0, 3) : []));

const WHITE_PILL =
  "rounded-full bg-white px-7 py-[13px] font-display text-[0.9rem] font-normal tracking-[0.04em] text-brand no-underline transition-colors hover:bg-brand-deep hover:text-white md:px-9 md:py-3.5 md:text-base";
const OUTLINE_PILL =
  "rounded-full border-2 border-white bg-transparent px-[22px] py-[11px] font-display text-[0.9rem] font-normal tracking-[0.04em] text-white no-underline transition-colors hover:border-brand-deep hover:bg-brand-deep md:px-[34px] md:py-3 md:text-base";
</script>

<template>
  <div class="single-event">
    <PageHeader
      :title="event.title"
      :lede="whenWhere"
      :crumbs="[
        { label: crumbHome, href: homeUrl },
        { label: crumbCalendar, href: calendarUrl },
      ]"
    >
      <template #before>
        <div class="flex flex-wrap items-center gap-3.5 md:gap-[18px]">
          <span aria-hidden="true" class="flex flex-col rounded-[12px] bg-white px-3.5 py-2.5 text-center text-brand md:rounded-[14px] md:px-[18px] md:py-3">
            <span class="font-display text-[1.4rem] leading-[1.05] md:text-[1.7rem]">{{ dayNum }}</span>
            <span class="text-[0.72rem] font-extrabold tracking-[0.1em] md:text-[0.8rem]">{{ monthShort }}</span>
          </span>
          <a :href="`${calendarUrl}?category=${event.cat}`" class="rounded-full bg-ink/[.22] px-3.5 py-[5px] text-[0.72rem] font-extrabold uppercase tracking-[0.06em] text-white no-underline hover:underline hover:underline-offset-4 md:px-4 md:py-1.5 md:text-[0.8rem]">
            {{ category.label }}
          </a>
        </div>
      </template>
      <div class="flex flex-wrap gap-2.5 md:gap-3.5">
        <a v-if="event.rsvpUrl" :href="event.rsvpUrl" target="_blank" rel="noopener" :class="WHITE_PILL">{{ rsvpLabel }}</a>
        <a v-if="event.icsUrl || event.gcalUrl" :href="event.icsUrl || event.gcalUrl" :class="OUTLINE_PILL">{{ addToCalendarLabel }}</a>
      </div>
    </PageHeader>

    <!-- Content + sidebar -->
    <section class="bg-white px-6 pb-14 pt-10 md:pb-24 md:pt-16" data-tone="white">
      <div class="mx-auto grid max-w-[1140px] items-start gap-10 lg:gap-14 lg:[grid-template-columns:minmax(300px,1fr)_310px]">
        <article class="flex min-w-0 flex-col gap-[18px] md:gap-6">
          <h2 v-if="hasBody" class="m-0 font-display text-[1.35rem] font-normal leading-[1.2] md:text-[clamp(1.6rem,2.6vw,2.2rem)] md:leading-[1.1]">{{ aboutLabel }}</h2>
          <figure v-if="hasImage" class="m-0 flex flex-col">
            <div class="aspect-video overflow-hidden rounded-[16px] bg-white md:rounded-[20px]">
              <ImageSlot :src="event.featuredImage.src" :alt="event.featuredImage.alt" loading="eager" />
            </div>
            <figcaption v-if="event.featuredImage.caption || event.featuredImage.credit" class="mt-3 text-[0.9rem] leading-[1.5] text-muted">
              {{ event.featuredImage.caption }} {{ event.featuredImage.credit }}
            </figcaption>
          </figure>
          <p v-if="event.summary" class="m-0 text-[1.08rem] font-semibold leading-[1.6] text-ink md:text-[1.22rem] md:leading-[1.65]">{{ event.summary }}</p>
          <EventBlocks :blocks="event.blocks" />
        </article>

        <aside
          aria-label="Event details"
          class="flex flex-col gap-6 lg:sticky lg:top-[calc(108px+var(--wp-admin--admin-bar--height,0px))] lg:max-h-[calc(100vh-124px)] lg:overflow-auto"
        >
          <LinkListCard :heading="detailsLabel" :rows="detailRows" class="[&_.row-label]:text-brand" />
          <CtaCard v-if="event.rsvpUrl" id="rsvp" :title="saveTitle" :body="saveBody" :href="event.rsvpUrl" :label="saveLabel" external />
          <DashedNote v-if="hasContact" :heading="contactLabel">
            <p v-if="event.contact.name" class="font-bold text-ink">{{ event.contact.name }}</p>
            <p v-if="event.contact.email"><a :href="`mailto:${event.contact.email}`">{{ event.contact.email }}</a></p>
            <p v-if="event.contact.phone"><a :href="`tel:${event.contact.phone.replace(/[^0-9+]/g, '')}`">{{ event.contact.phone }}</a></p>
          </DashedNote>
        </aside>
      </div>
    </section>

    <!-- More upcoming events -->
    <section v-if="moreEvents.length > 0" class="bg-alt px-6 pb-14 pt-11 md:pb-24 md:pt-16" data-tone="alt">
      <div class="mx-auto flex max-w-[1140px] flex-col gap-[18px] md:gap-7">
        <div class="flex flex-wrap items-baseline justify-between gap-4">
          <h2 class="m-0 font-display text-[1.35rem] font-normal leading-[1.2] md:text-[clamp(1.6rem,2.8vw,2.2rem)] md:leading-[1.1]">{{ moreLabel }}</h2>
          <a :href="calendarUrl" class="hidden items-center gap-4 text-[1.05rem] font-extrabold uppercase tracking-[0.03em] text-accent no-underline hover:underline hover:underline-offset-4 md:flex">
            {{ fullCalendarLabel }}
            <svg aria-hidden="true" focusable="false" viewBox="0 0 40 20" class="h-5 w-10 flex-none fill-accent"><path d="M0 8.4h26v3.2H0z" /><path d="M24 1.5 38.5 10 24 18.5Z" /></svg>
          </a>
        </div>
        <div class="flex flex-col gap-3">
          <EventCard v-for="ev in moreEvents" :key="ev.id" :event="ev" :fallback-url="calendarUrl" :view-label="viewLabel" subtle />
        </div>
        <a :href="calendarUrl" class="flex items-center justify-center gap-3.5 text-[0.95rem] font-extrabold uppercase tracking-[0.03em] text-accent no-underline hover:underline hover:underline-offset-4 md:hidden">
          {{ fullCalendarLabel }}
          <svg aria-hidden="true" focusable="false" viewBox="0 0 40 20" class="h-[17px] w-[34px] flex-none fill-accent"><path d="M0 8.4h26v3.2H0z" /><path d="M24 1.5 38.5 10 24 18.5Z" /></svg>
        </a>
      </div>
    </section>
  </div>
</template>

// next-js/components/site/SingleEvent.tsx
import { CtaCard } from "@/components/site/CtaCard";
import { DashedNote } from "@/components/site/DashedNote";
import { EventBlocks } from "@/components/site/EventBlocks";
import { LinkListCard } from "@/components/site/LinkListCard";
import { PageHeader } from "@/components/site/PageHeader";
import { SiteLink } from "@/components/site/SiteLink";
import { ImageSlot } from "@/components/site/blog/ImageSlot";
import { EventCard } from "@/components/site/calendar/EventCard";
import { dateTile } from "@/lib/calendar";
import { categoryById, eventCategories } from "@/lib/categories";
import { eventDetailRows, eventHasContact, eventWhenWhere, telHref } from "@/lib/event";
import type { EventCategory, RelatedEvent, SingleEventData } from "@/lib/schemas";

/* Single event (openspec progress-now-v4-events D4, specs "Event hero" …
 * "More upcoming events"; twin of views/single-event.twig / SingleEvent.vue).
 * Hero = PageHeader with extras (white date tile + translucent-ink category
 * pill before the h1; when/where lede; RSVP + Add-to-calendar pills). Content
 * = "About this event" + event blocks; sticky sidebar = Details rows (Date /
 * Time / Location) + "Save your spot" CtaCard (omitted without an RSVP link) +
 * contact note; "More upcoming events" = EventCard rows on the alt band.
 * Server component throughout — nothing here needs client JavaScript. */
export interface SingleEventLabels {
  crumbHome: string;
  crumbCalendar: string;
  breadcrumbLabel: string;
  rsvpLabel: string;
  addToCalendarLabel: string;
  aboutLabel: string;
  detailsLabel: string;
  dateLabel: string;
  timeLabel: string;
  locationLabel: string;
  saveTitle: string;
  saveBody: string;
  saveLabel: string;
  contactLabel: string;
  moreLabel: string;
  fullCalendarLabel: string;
  viewLabel: string;
  sidebarLabel: string;
}

export const DEFAULT_EVENT_LABELS: SingleEventLabels = {
  crumbHome: "Home",
  crumbCalendar: "Calendar",
  breadcrumbLabel: "Breadcrumb",
  rsvpLabel: "RSVP",
  addToCalendarLabel: "Add to calendar",
  aboutLabel: "About this event",
  detailsLabel: "Details",
  dateLabel: "Date",
  timeLabel: "Time",
  locationLabel: "Location",
  saveTitle: "Save your spot",
  saveBody: "RSVP and we’ll send the details straight to you.",
  saveLabel: "RSVP Now",
  contactLabel: "Questions? Contact",
  moreLabel: "More upcoming events",
  fullCalendarLabel: "Full calendar",
  viewLabel: "View event",
  sidebarLabel: "Event details",
};

const WHITE_PILL =
  "rounded-full bg-white px-7 py-[13px] font-display text-[0.9rem] font-normal tracking-[0.04em] text-brand no-underline transition-colors hover:bg-brand-deep hover:text-white md:px-9 md:py-3.5 md:text-base";
const OUTLINE_PILL =
  "rounded-full border-2 border-white bg-transparent px-[22px] py-[11px] font-display text-[0.9rem] font-normal tracking-[0.04em] text-white no-underline transition-colors hover:border-brand-deep hover:bg-brand-deep md:px-[34px] md:py-3 md:text-base";
const ARROW = (cls: string) => (
  <svg aria-hidden="true" focusable="false" viewBox="0 0 40 20" className={cls}>
    <path d="M0 8.4h26v3.2H0z" />
    <path d="M24 1.5 38.5 10 24 18.5Z" />
  </svg>
);

export function SingleEvent({
  event,
  categories,
  related = [],
  showRelated = true,
  homeUrl = "/",
  calendarUrl = "/calendar/",
  labels = {},
  wpOrigin,
}: {
  event: SingleEventData;
  /** WP term-driven categories — replaces the registry palette when provided */
  categories?: EventCategory[] | null;
  related?: RelatedEvent[];
  showRelated?: boolean;
  homeUrl?: string;
  calendarUrl?: string;
  labels?: Partial<SingleEventLabels>;
  wpOrigin: string;
}) {
  const L: SingleEventLabels = {
    ...DEFAULT_EVENT_LABELS,
    ...Object.fromEntries(Object.entries(labels).filter(([, v]) => Boolean(v))),
  };
  const category = categoryById(event.cat, eventCategories(categories));
  const tile = dateTile(event.date);
  const hasImage = Boolean(event.featuredImage.src);
  const hasBody = hasImage || event.summary !== "" || event.blocks.length > 0;
  const moreEvents = showRelated ? related.slice(0, 3) : [];
  const addToCalendar = event.icsUrl || event.gcalUrl;
  const rows = eventDetailRows(event, {
    date: L.dateLabel,
    time: L.timeLabel,
    location: L.locationLabel,
  });

  return (
    <div className="single-event contents" data-route-kind="event">
      <PageHeader
        title={event.title}
        lede={eventWhenWhere(event)}
        breadcrumbLabel={L.breadcrumbLabel}
        crumbs={[
          { label: L.crumbHome, href: homeUrl },
          { label: L.crumbCalendar, href: calendarUrl },
        ]}
        before={
          <div className="flex flex-wrap items-center gap-3.5 md:gap-[18px]">
            <span
              aria-hidden="true"
              className="flex flex-col rounded-[12px] bg-white px-3.5 py-2.5 text-center text-brand md:rounded-[14px] md:px-[18px] md:py-3"
            >
              <span className="font-display text-[1.4rem] leading-[1.05] md:text-[1.7rem]">
                {tile.day}
              </span>
              <span className="text-[0.72rem] font-extrabold tracking-[0.1em] md:text-[0.8rem]">
                {tile.month}
              </span>
            </span>
            <SiteLink
              href={`${calendarUrl}?category=${event.cat}`}
              wpOrigin={wpOrigin}
              className="rounded-full bg-ink/[.22] px-3.5 py-[5px] text-[0.72rem] font-extrabold uppercase tracking-[0.06em] text-white no-underline hover:underline hover:underline-offset-4 md:px-4 md:py-1.5 md:text-[0.8rem]"
            >
              {category.label}
            </SiteLink>
          </div>
        }
        wpOrigin={wpOrigin}
      >
        {event.rsvpUrl || addToCalendar ? (
          <div className="flex flex-wrap gap-2.5 md:gap-3.5">
            {event.rsvpUrl ? (
              <a href={event.rsvpUrl} target="_blank" rel="noopener" className={WHITE_PILL}>
                {L.rsvpLabel}
                <span className="sr-only"> (opens in a new tab)</span>
              </a>
            ) : null}
            {addToCalendar ? (
              <SiteLink href={addToCalendar} wpOrigin={wpOrigin} className={OUTLINE_PILL}>
                {L.addToCalendarLabel}
              </SiteLink>
            ) : null}
          </div>
        ) : null}
      </PageHeader>

      {/* Content + sidebar */}
      <section className="bg-white px-6 pb-14 pt-10 md:pb-24 md:pt-16" data-tone="white">
        <div className="mx-auto grid max-w-[1140px] items-start gap-10 lg:gap-14 lg:[grid-template-columns:minmax(300px,1fr)_310px]">
          <article className="flex min-w-0 flex-col gap-[18px] md:gap-6">
            {hasBody ? (
              <h2 className="m-0 font-display text-[1.35rem] font-normal leading-[1.2] md:text-[clamp(1.6rem,2.6vw,2.2rem)] md:leading-[1.1]">
                {L.aboutLabel}
              </h2>
            ) : null}
            {hasImage ? (
              <figure className="m-0 flex flex-col">
                <div className="aspect-video overflow-hidden rounded-[16px] bg-white md:rounded-[20px]">
                  <ImageSlot
                    src={event.featuredImage.src}
                    alt={event.featuredImage.alt}
                    priority
                    sizes="(min-width: 1140px) 780px, 100vw"
                  />
                </div>
                {event.featuredImage.caption || event.featuredImage.credit ? (
                  <figcaption className="mt-3 text-[0.9rem] leading-[1.5] text-muted">
                    {[event.featuredImage.caption, event.featuredImage.credit]
                      .filter(Boolean)
                      .join(" ")}
                  </figcaption>
                ) : null}
              </figure>
            ) : null}
            {event.summary ? (
              <p className="m-0 text-[1.08rem] font-semibold leading-[1.6] text-ink md:text-[1.22rem] md:leading-[1.65]">
                {event.summary}
              </p>
            ) : null}
            <EventBlocks blocks={event.blocks} />
          </article>

          <aside
            aria-label={L.sidebarLabel}
            className="flex flex-col gap-6 lg:sticky lg:top-[calc(108px+var(--wp-admin--admin-bar--height,0px))] lg:max-h-[calc(100vh-124px)] lg:overflow-auto"
          >
            <LinkListCard
              heading={L.detailsLabel}
              rows={rows}
              className="[&_.row-label]:text-brand"
              wpOrigin={wpOrigin}
            />
            {event.rsvpUrl ? (
              <CtaCard
                id="rsvp"
                title={L.saveTitle}
                body={L.saveBody}
                href={event.rsvpUrl}
                label={L.saveLabel}
                external
                wpOrigin={wpOrigin}
              />
            ) : null}
            {eventHasContact(event) ? (
              <DashedNote heading={L.contactLabel}>
                {event.contact.name ? (
                  <p className="font-bold text-ink">{event.contact.name}</p>
                ) : null}
                {event.contact.email ? (
                  <p>
                    <a href={`mailto:${event.contact.email}`}>{event.contact.email}</a>
                  </p>
                ) : null}
                {event.contact.phone ? (
                  <p>
                    <a href={telHref(event.contact.phone)}>{event.contact.phone}</a>
                  </p>
                ) : null}
              </DashedNote>
            ) : null}
          </aside>
        </div>
      </section>

      {moreEvents.length > 0 ? (
        <section
          className="bg-alt px-6 pb-14 pt-11 md:pb-24 md:pt-16"
          data-tone="alt"
          data-more-events=""
        >
          <div className="mx-auto flex max-w-[1140px] flex-col gap-[18px] md:gap-7">
            <div className="flex flex-wrap items-baseline justify-between gap-4">
              <h2 className="m-0 font-display text-[1.35rem] font-normal leading-[1.2] md:text-[clamp(1.6rem,2.8vw,2.2rem)] md:leading-[1.1]">
                {L.moreLabel}
              </h2>
              <SiteLink
                href={calendarUrl}
                wpOrigin={wpOrigin}
                className="hidden items-center gap-4 text-[1.05rem] font-extrabold uppercase tracking-[0.03em] text-accent no-underline hover:underline hover:underline-offset-4 md:flex"
              >
                {L.fullCalendarLabel}
                {ARROW("h-5 w-10 flex-none fill-accent")}
              </SiteLink>
            </div>
            <div className="flex flex-col gap-3">
              {moreEvents.map((ev) => (
                <EventCard
                  key={ev.id}
                  event={ev}
                  fallbackUrl={calendarUrl}
                  viewLabel={L.viewLabel}
                  subtle
                  wpOrigin={wpOrigin}
                />
              ))}
            </div>
            <SiteLink
              href={calendarUrl}
              wpOrigin={wpOrigin}
              className="flex items-center justify-center gap-3.5 text-[0.95rem] font-extrabold uppercase tracking-[0.03em] text-accent no-underline hover:underline hover:underline-offset-4 md:hidden"
            >
              {L.fullCalendarLabel}
              {ARROW("h-[17px] w-[34px] flex-none fill-accent")}
            </SiteLink>
          </div>
        </section>
      ) : null}
    </div>
  );
}
