// site/app/components/routes/RouteEvent.vue
<script setup lang="ts">
import { computed } from "vue";
import SingleEvent from "@/components/site/SingleEvent.vue";
import { fetchSingleEvent } from "@/lib/api";
import { eventKey } from "@/lib/chapter/keys";
import type { ResolvedRoute } from "@/lib/chapter/routes";
import {
  payloadSlug,
  provideRouteLanguages,
  useChapterApi,
  useChapterData,
  useChapterSite,
  useRouteSeo,
} from "@/composables/useChapter";

/* Single event — views/single-event.twig. SingleEvent renders the v4 hero
 * through PageHeader; sidebar/strip copy comes from the site strings. */
const props = defineProps<{ resolved: ResolvedRoute }>();

const lang = computed(() => props.resolved.lang);
const slug = payloadSlug(props.resolved.route!);
const api = useChapterApi();
const { data: site } = await useChapterSite(lang.value);
const { data: event } = await useChapterData(eventKey(lang.value, slug), () =>
  fetchSingleEvent(api, slug, lang.value),
);

provideRouteLanguages(computed(() => event.value?.languages));
useRouteSeo(
  computed(() => event.value?.seo),
  lang,
);

const str = (key: string, fallback: string) => site.value?.strings[key] || fallback;
const labels = computed(() => ({
  crumbHome: str("blog_crumb_home", "Home"),
  crumbCalendar: str("cal_crumb_calendar", "Calendar"),
  rsvpLabel: str("event_rsvp", "RSVP"),
  addToCalendarLabel: str("event_add_calendar", "Add to calendar"),
  aboutLabel: str("event_about", "About this event"),
  detailsLabel: str("event_details", "Details"),
  dateLabel: str("event_date", "Date"),
  timeLabel: str("event_time", "Time"),
  locationLabel: str("event_location", "Location"),
  saveTitle: str("event_save_h", "Save your spot"),
  saveBody: str("event_save_p", "RSVP and we’ll send the details straight to you."),
  saveLabel: str("event_save_cta", "RSVP Now"),
  contactLabel: str("event_contact", "Questions? Contact"),
  moreLabel: str("event_more", "More upcoming events"),
  fullCalendarLabel: str("home_events_all", "Full calendar"),
  viewLabel: str("home_view_event", "View event"),
}));
</script>

<template>
  <SingleEvent
    v-if="event"
    :event="event.event"
    :categories="event.categories"
    :related="event.related"
    :show-related="event.showRelated"
    :home-url="event.homeUrl"
    :calendar-url="event.calendarUrl"
    v-bind="labels"
  />
</template>

// next-js/components/routes/RouteEvent.tsx
import { notFound } from "next/navigation";
import type { RouteProps } from "@/components/routes/types";
import { SingleEvent, type SingleEventLabels } from "@/components/site/SingleEvent";
import { getEvent, getSite } from "@/lib/data";
import { getEnv } from "@/lib/env";
import { payloadSlug } from "@/lib/routes";
import type { SiteEnvelope } from "@/lib/schemas";

/* Single event — views/single-event.twig / RouteEvent.vue. The envelope carries
 * its own home/calendar URLs (WordPress absolute; SiteLink re-homes them);
 * sidebar/strip copy comes from the site strings. */
export async function RouteEvent({ resolved }: RouteProps) {
  const [envelope, site] = await Promise.all([
    resolved.route ? getEvent(payloadSlug(resolved.route), resolved.lang) : null,
    getSite(resolved.lang),
  ]);
  if (!envelope) notFound();
  return (
    <SingleEvent
      event={envelope.event}
      categories={envelope.categories.length ? envelope.categories : site.categories}
      related={envelope.related}
      showRelated={envelope.showRelated}
      homeUrl={envelope.homeUrl}
      calendarUrl={envelope.calendarUrl}
      labels={eventLabels(site)}
      wpOrigin={getEnv().WP_ORIGIN}
    />
  );
}

export function eventLabels(site: SiteEnvelope): Partial<SingleEventLabels> {
  const s = site.strings as Record<string, string>;
  const str = (key: string) => s[key] || undefined;
  return {
    crumbHome: str("blog_crumb_home"),
    crumbCalendar: str("cal_crumb_calendar"),
    breadcrumbLabel: str("blog_crumb_label"),
    rsvpLabel: str("event_rsvp"),
    addToCalendarLabel: str("event_add_calendar"),
    aboutLabel: str("event_about"),
    detailsLabel: str("event_details"),
    dateLabel: str("event_date"),
    timeLabel: str("event_time"),
    locationLabel: str("event_location"),
    saveTitle: str("event_save_h"),
    saveBody: str("event_save_p"),
    saveLabel: str("event_save_cta"),
    contactLabel: str("event_contact"),
    moreLabel: str("event_more"),
    fullCalendarLabel: str("home_events_all"),
    viewLabel: str("home_view_event"),
  };
}
