// next-js/components/site/calendar/EventCalendar.tsx
"use client";

import { useEffect, useId, useRef, useState } from "react";
import { EventDetailDialog } from "@/components/site/calendar/EventDetailDialog";
import { EventListView } from "@/components/site/calendar/EventListView";
import { MonthGrid } from "@/components/site/calendar/MonthGrid";
import {
  addMonths,
  calendarHref,
  eventsInMonth,
  filterByCategory,
  monthBounds,
  monthInWindow,
  monthKey,
  monthLabel,
  monthOf,
  type EventWindow,
  type YearMonth,
} from "@/lib/calendar";
import { eventCategories } from "@/lib/categories";
import type { ChapterEvent, EventCategory } from "@/lib/schemas";
import { cn } from "@/lib/utils";

/* Calendar island (openspec progress-now-v4-events D1/D2/D5; next-headless-site
 * § Interactive archive and calendar). The server renders the requested month
 * from the REST window it fetched (−1 → +12 months) and hands it over as props;
 * the island owns month paging, the Month/List toggle, the category filter
 * chips (FILTER: All events / term chips with swatch dots, as on the reference
 * site) and the preview dialog.
 * URL state (`?view=`, `?month=`, `?category=`) is written with
 * history.replaceState so a reload or a shared link lands on the same month.
 * Months outside the window load through the same-origin /api/events with a
 * live status; the failure state keeps the ICS feed reachable. */
export interface CalendarLabels {
  monthLabelText: string;
  listLabelText: string;
  viewGroupLabel: string;
  filterLabel: string;
  allEventsLabel: string;
  prevLabel: string;
  nextLabel: string;
  viewLabel: string;
  rsvpLabel: string;
  closeLabel: string;
  emptyTitle: string;
  emptyBody: string;
  loading: string;
  errorTitle: string;
  errorBody: string;
  retry: string;
  icsLabel: string;
}

export const DEFAULT_CALENDAR_LABELS: CalendarLabels = {
  monthLabelText: "Month",
  listLabelText: "List",
  viewGroupLabel: "View",
  filterLabel: "Filter:",
  allEventsLabel: "All events",
  prevLabel: "Previous month",
  nextLabel: "Next month",
  viewLabel: "View event",
  rsvpLabel: "RSVP",
  closeLabel: "Close",
  emptyTitle: "Nothing scheduled this month",
  emptyBody: "Check the next month or subscribe below and never miss one.",
  loading: "Loading events…",
  errorTitle: "We couldn’t load the calendar",
  errorBody: "Try again in a moment — or subscribe with",
  retry: "Retry",
  icsLabel: "iCal / .ics",
};

const NAV_BTN =
  "inline-flex size-11 flex-none cursor-pointer items-center justify-center rounded-full border-2 border-control bg-white p-0 text-[1.1rem] font-extrabold text-ink transition-colors hover:border-accent hover:bg-accent hover:text-white";
const CHIP =
  "inline-flex cursor-pointer items-center gap-2 rounded-full border px-3.5 py-2 text-[0.85rem] font-bold leading-[1.5] transition-colors";
const SEG_BTN =
  "cursor-pointer rounded-full border-none px-[22px] py-[9px] font-display text-[0.9rem] font-normal tracking-[0.03em] transition-colors";

type MonthState =
  | { status: "ready"; events: ChapterEvent[] }
  | { status: "loading" }
  | { status: "failed" };

export function EventCalendar({
  events,
  window,
  todayISO,
  lang,
  initialView = "month",
  defaultView = "month",
  initialMonth,
  category: initialCategory = "all",
  categories,
  showCategoryColors = true,
  basePath,
  icsUrl,
  fetchImpl,
  labels = {},
  wpOrigin,
}: {
  /** the server-fetched REST window */
  events: ChapterEvent[];
  window: EventWindow;
  /** the server's yyyy-mm-dd — keeps "today" identical across SSR and hydration */
  todayISO: string;
  lang: string;
  initialView?: "month" | "list";
  defaultView?: "month" | "list";
  initialMonth?: YearMonth;
  /** initial `?category=` (the chips write it back) */
  category?: string;
  categories?: EventCategory[] | null;
  showCategoryColors?: boolean;
  /** calendar page path (URL state + event fallback link) */
  basePath: string;
  icsUrl: string;
  /** test seam for the out-of-window fetch */
  fetchImpl?: typeof fetch;
  labels?: Partial<CalendarLabels>;
  wpOrigin: string;
}) {
  const L: CalendarLabels = {
    ...DEFAULT_CALENDAR_LABELS,
    ...Object.fromEntries(Object.entries(labels).filter(([, v]) => Boolean(v))),
  };
  const currentMonth = monthOf(todayISO);
  const [view, setView] = useState<"month" | "list">(initialView);
  const [ym, setYm] = useState<YearMonth>(initialMonth ?? currentMonth);
  const [category, setCategory] = useState(initialCategory);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const palette = eventCategories(categories);
  const [extra, setExtra] = useState<Record<string, MonthState>>({});
  const [retryTick, setRetryTick] = useState(0);
  /** months already requested (ref: read/written only in effects and handlers) */
  const requested = useRef(new Set<string>());
  const headingId = useId();
  const mounted = useRef(false);
  const openerRef = useRef<HTMLElement | null>(null);
  const select = (id: string) => {
    openerRef.current = document.activeElement as HTMLElement | null;
    setSelectedId(id);
  };
  const key = monthKey(ym);
  const inWindow = monthInWindow(ym, window);

  // URL is the state (replaceState keeps Next's router in sync without a server round trip).
  useEffect(() => {
    if (!mounted.current) {
      mounted.current = true;
      return;
    }
    const href = calendarHref(
      basePath,
      { view, month: key, category },
      { view: defaultView, month: monthKey(currentMonth) },
    );
    const current = `${location.pathname}${location.search}`;
    if (current !== href) globalThis.history.replaceState(null, "", href);
    // eslint-disable-next-line react-hooks/exhaustive-deps -- currentMonth derives from todayISO
  }, [view, key, category, basePath, defaultView, todayISO]);

  // Out-of-window months: fetch once per month, same-origin, with a live status.
  useEffect(() => {
    if (inWindow || requested.current.has(key)) return;
    requested.current.add(key);
    const controller = new AbortController();
    const load = async () => {
      setExtra((s) => ({ ...s, [key]: { status: "loading" } }));
      try {
        const b = monthBounds(ym);
        const q = new URLSearchParams({ lang, from: b.from, to: b.to });
        // trailing slash: the app redirects `/api/events` → `/api/events/` (one request, not two)
        const res = await (fetchImpl ?? fetch)(`/api/events/?${q}`, { signal: controller.signal });
        if (!res.ok) throw new Error(String(res.status));
        const json = (await res.json()) as { events?: unknown };
        if (!Array.isArray(json.events)) throw new Error("shape");
        setExtra((s) => ({
          ...s,
          [key]: { status: "ready", events: json.events as ChapterEvent[] },
        }));
      } catch {
        // Aborted (month changed mid-flight): forget the stale "loading" so a revisit refetches.
        if (controller.signal.aborted) requested.current.delete(key);
        setExtra((s) => {
          const next = { ...s };
          if (controller.signal.aborted) delete next[key];
          else next[key] = { status: "failed" };
          return next;
        });
      }
    };
    void load();
    return () => controller.abort();
    // eslint-disable-next-line react-hooks/exhaustive-deps -- ym is derived from key
  }, [key, inWindow, retryTick, lang, fetchImpl]);

  const monthState: MonthState = inWindow
    ? { status: "ready", events }
    : (extra[key] ?? { status: "loading" });
  const pool = monthState.status === "ready" ? filterByCategory(monthState.events, category) : [];
  const monthEvents = eventsInMonth(pool, ym);
  const selected =
    (monthState.status === "ready" ? monthState.events : events).find((e) => e.id === selectedId) ??
    null;
  const changeMonth = (delta: number) => setYm((m) => addMonths(m, delta));
  const retry = () => {
    requested.current.delete(key);
    setExtra((s) => {
      const next = { ...s };
      delete next[key];
      return next;
    });
    setRetryTick((t) => t + 1);
  };

  return (
    <div className="event-calendar" data-calendar="" data-testid="event-calendar" data-view={view}>
      {/* Toolbar: month nav + Month/List segmented control */}
      <section
        className="bg-white px-6 pt-7 md:pt-10"
        data-tone="white"
        data-testid="event-calendar-toolbar"
      >
        <div className="mx-auto flex max-w-[1200px] flex-col gap-5">
          <div className="flex flex-col gap-4 md:flex-row md:flex-wrap md:items-center md:justify-between md:gap-5">
            <div className="flex items-center justify-between gap-2.5 md:justify-start md:gap-3.5">
              <button
                type="button"
                aria-label={L.prevLabel}
                className={NAV_BTN}
                data-testid="event-calendar-prev-month"
                onClick={() => changeMonth(-1)}
              >
                <span aria-hidden="true">←</span>
              </button>
              <h2
                id={headingId}
                aria-live="polite"
                data-testid="event-calendar-month-label"
                data-month={key}
                className="m-0 text-center font-display text-[1.25rem] font-normal md:min-w-[280px] md:text-[clamp(1.3rem,2.4vw,1.8rem)]"
              >
                {monthLabel(ym)}
              </h2>
              <button
                type="button"
                aria-label={L.nextLabel}
                className={NAV_BTN}
                data-testid="event-calendar-next-month"
                onClick={() => changeMonth(1)}
              >
                <span aria-hidden="true">→</span>
              </button>
            </div>
            <div
              role="group"
              aria-label={L.viewGroupLabel}
              className="flex items-center gap-0.5 self-center rounded-full bg-alt p-1 md:self-auto"
              data-testid="event-calendar-view-switch"
            >
              {(["month", "list"] as const).map((v) => (
                <button
                  key={v}
                  type="button"
                  aria-pressed={view === v}
                  className={cn(
                    SEG_BTN,
                    view === v
                      ? "bg-brand text-white"
                      : "bg-transparent text-ink hover:bg-control-faint",
                  )}
                  data-testid="event-calendar-view-option"
                  data-view={v}
                  onClick={() => setView(v)}
                >
                  {v === "month" ? L.monthLabelText : L.listLabelText}
                </button>
              ))}
            </div>
          </div>

          {/* Category filter chips: "All events" + one per term, swatch dot in term color */}
          <div
            role="group"
            aria-label={L.filterLabel}
            className="flex flex-wrap items-center gap-2"
            data-testid="event-calendar-filters"
          >
            <span className="mr-1.5 font-display text-[0.82rem] font-bold uppercase tracking-[0.06em] text-muted">
              {L.filterLabel}
            </span>
            {palette.map((cat) => (
              <button
                key={cat.id}
                type="button"
                aria-pressed={category === cat.id}
                className={cn(
                  CHIP,
                  category === cat.id
                    ? "border-ink bg-ink text-white"
                    : "border-control bg-white text-ink hover:border-ink",
                )}
                data-testid="event-calendar-filter-option"
                data-category={cat.id}
                onClick={() => setCategory(cat.id)}
              >
                {showCategoryColors && cat.color ? (
                  <span
                    aria-hidden="true"
                    className="inline-block size-2.5 flex-none rounded-full"
                    style={{ backgroundColor: cat.color }}
                  />
                ) : null}
                {cat.id === "all" ? L.allEventsLabel : cat.label}
              </button>
            ))}
          </div>
        </div>
      </section>

      {monthState.status === "loading" ? (
        <section
          className="bg-white px-4 pb-8 pt-5 min-[700px]:px-6 md:pb-14 md:pt-7"
          data-tone="white"
          aria-busy="true"
          data-testid="event-calendar-loading-section"
        >
          <div
            aria-hidden="true"
            className="mx-auto max-w-[1200px] overflow-hidden rounded-[20px] shadow-gallery"
            data-testid="calendar-skeleton"
          >
            <div className="h-11 animate-pulse bg-brand/30" />
            <div className="grid grid-cols-7 gap-px bg-line pt-px">
              {Array.from({ length: 35 }, (_, n) => (
                <div key={n} className="h-11 animate-pulse bg-alt min-[700px]:h-24" />
              ))}
            </div>
          </div>
          <p
            role="status"
            className="mx-auto mt-3.5 max-w-[1200px] text-[0.9rem] font-medium text-muted"
            data-testid="event-calendar-loading"
          >
            {L.loading}
          </p>
        </section>
      ) : monthState.status === "failed" ? (
        <section className="bg-white px-6 pb-10 pt-5 md:pb-14 md:pt-7" data-tone="white">
          <div className="mx-auto max-w-[900px]">
            <div
              role="alert"
              className="flex flex-col items-center gap-1 rounded-[16px] border-2 border-dashed border-border-muted px-6 py-11 text-center md:rounded-[20px] md:px-8 md:py-16"
              data-calendar-error=""
              data-testid="event-calendar-error"
            >
              <div
                className="text-[1.05rem] font-extrabold md:text-[1.25rem] md:font-bold"
                data-testid="event-calendar-error-title"
              >
                {L.errorTitle}
              </div>
              <p
                className="m-0 max-w-[44ch] text-base font-medium leading-[1.45] md:text-[1.2rem]"
                data-testid="event-calendar-error-body"
              >
                {L.errorBody}{" "}
                <a
                  href={icsUrl}
                  className="font-bold text-accent underline underline-offset-4 hover:text-brand-deep"
                  data-testid="event-calendar-error-ics-link"
                >
                  {L.icsLabel}
                </a>{" "}
                and get every event straight in your own calendar.
              </p>
              <button
                type="button"
                className="mt-4 cursor-pointer rounded-full border-2 border-accent bg-transparent px-6 py-2.5 text-[0.92rem] font-bold text-accent transition-colors hover:bg-accent hover:text-white"
                data-testid="event-calendar-retry"
                onClick={retry}
              >
                {L.retry}
              </button>
            </div>
          </div>
        </section>
      ) : view === "month" ? (
        <section
          className="bg-white px-4 pb-8 pt-5 min-[700px]:px-6 md:pb-14 md:pt-7"
          data-tone="white"
          data-testid="event-calendar-month-section"
        >
          <div className="mx-auto max-w-[1200px]">
            <MonthGrid
              ym={ym}
              events={pool}
              todayISO={todayISO}
              categories={categories}
              showCategoryColors={showCategoryColors}
              labelledBy={headingId}
              onSelect={select}
              onMonthChange={changeMonth}
            />
          </div>
        </section>
      ) : (
        <section
          className="bg-white px-6 pb-10 pt-5 md:pb-14 md:pt-7"
          data-tone="white"
          data-testid="event-calendar-list-section"
        >
          <div className="mx-auto max-w-[900px]">
            <EventListView
              events={monthEvents}
              fallbackUrl={basePath}
              viewLabel={L.viewLabel}
              emptyTitle={L.emptyTitle}
              emptyBody={L.emptyBody}
              wpOrigin={wpOrigin}
            />
          </div>
        </section>
      )}

      <EventDetailDialog
        event={selected}
        categories={categories}
        showCategoryColors={showCategoryColors}
        fallbackUrl={basePath}
        viewLabel={L.viewLabel}
        rsvpLabel={L.rsvpLabel}
        closeLabel={L.closeLabel}
        openerRef={openerRef}
        onClose={() => setSelectedId(null)}
        wpOrigin={wpOrigin}
      />
    </div>
  );
}

// nuxt-js/app/components/site/EventCalendar.vue
<script setup lang="ts">
/* Calendar island (openspec progress-now-v4-events D1/D2/D5, specs "Calendar
 * toolbar" … "Calendar subscribe strip"). Month/list state, URL state and the
 * windowed REST fetch are unchanged (island-data-fetch); only the skin is v4:
 * round month buttons + Bowlby label + segmented Month/List on an alt pill,
 * the v4 MonthGrid (dots + legend under 700px), EventCard list rows, the
 * dashed empty month, and the ink subscribe strip with Google / iCal pills.
 * The category filter row (FILTER: + "All events" / term chips with swatch
 * dots) sits under the toolbar as on the reference site; `?category=` keeps
 * the active chip across reloads. */
import { computed, onMounted, ref, watch } from "vue";
import EventDetailDialog from "@/components/site/EventDetailDialog.vue";
import EventListView from "@/components/site/EventListView.vue";
import MonthGrid from "@/components/site/MonthGrid.vue";
import { fetchEvents, isAbortError } from "@/lib/api";
import { currentSearch, replaceSearch } from "@/lib/url-state";
import {
  type ChapterEvent,
  EVENT_CATEGORIES,
  MONTH_NAMES,
  parseISODate,
  setCategories,
} from "@/lib/events";

const props = withDefaults(
  defineProps<{
    /** progressnow/v1 base URL — the island fetches its window on mount */
    apiBase: string;
    /** Polylang language slug of the page; scopes the fetched events to it */
    lang?: string;
    defaultView?: "month" | "list";
    showCategoryColors?: boolean;
    showSubscribe?: boolean;
    googleCalUrl?: string;
    icsUrl?: string;
    /** translated copy */
    subscribeTitle?: string;
    subscribeLede?: string;
    googleLabel?: string;
    icsLabel?: string;
    monthLabelText?: string;
    listLabelText?: string;
    filterLabelText?: string;
    allEventsText?: string;
    viewLabel?: string;
    emptyTitle?: string;
    emptyBody?: string;
  }>(),
  {
    defaultView: "month",
    showCategoryColors: true,
    showSubscribe: true,
    googleCalUrl: "#",
    icsUrl: "#",
    subscribeTitle: "Subscribe to the calendar",
    subscribeLede: "Add every meeting and action to your own calendar automatically.",
    googleLabel: "Google Calendar",
    icsLabel: "iCal / .ics",
    monthLabelText: "Month",
    listLabelText: "List",
    filterLabelText: "Filter:",
    allEventsText: "All events",
    viewLabel: "View event",
    emptyTitle: "Nothing scheduled this month",
    emptyBody: "Check the next month or subscribe below and never miss one.",
  },
);

/* ---- windowed fetch (island-data-fetch): skeleton until events land ---- */
const events = ref<ChapterEvent[]>([]);
const loading = ref(true);
const failed = ref(false);

async function loadEvents() {
  loading.value = true;
  failed.value = false;
  try {
    const envelope = await fetchEvents(props.apiBase, { lang: props.lang });
    events.value = envelope.events;
    if (envelope.categories.length > 0) setCategories(envelope.categories);
  } catch (err) {
    if (isAbortError(err)) return;
    failed.value = true;
  } finally {
    loading.value = false;
  }
}

onMounted(loadEvents);

/* ---- state (view + filter survive reload via URL params) ---- */
const initialParams = new URLSearchParams(currentSearch());
const initialView = initialParams.get("view");
const initialCat = initialParams.get("category");

const view = ref<"month" | "list">(
  initialView === "month" || initialView === "list" ? initialView : props.defaultView,
);
const activeCat = ref(
  EVENT_CATEGORIES.some((c) => c.id === initialCat && c.id !== "all")
    ? (initialCat as string)
    : "all",
);
const monthOffset = ref(0);
const selectedId = ref<string | null>(null);

watch([view, activeCat], () => {
  const params = new URLSearchParams(currentSearch());
  if (view.value === props.defaultView) params.delete("view");
  else params.set("view", view.value);
  if (activeCat.value === "all") params.delete("category");
  else params.set("category", activeCat.value);
  replaceSearch(params);
});

/* ---- month math ---- */
const now = new Date();
const visibleMonth = computed(() => {
  const base = new Date(now.getFullYear(), now.getMonth() + monthOffset.value, 1);
  return { year: base.getFullYear(), month: base.getMonth() };
});
const monthLabel = computed(
  () => `${MONTH_NAMES[visibleMonth.value.month]} ${visibleMonth.value.year}`,
);

/* ---- filtering ---- */
const filtered = computed(() =>
  events.value.filter((e) => activeCat.value === "all" || e.cat === activeCat.value),
);
const monthEvents = computed(() =>
  filtered.value
    .filter((e) => {
      const d = parseISODate(e.date);
      return (
        d.getFullYear() === visibleMonth.value.year && d.getMonth() === visibleMonth.value.month
      );
    })
    .sort((a, b) => a.date.localeCompare(b.date)),
);

const selectedEvent = computed(
  () => events.value.find((e) => e.id === selectedId.value) ?? null,
);

const NAV_BTN =
  "inline-flex size-11 flex-none cursor-pointer items-center justify-center rounded-full border-2 border-control bg-white p-0 text-[1.1rem] font-extrabold text-ink transition-colors hover:border-accent hover:bg-accent hover:text-white";
const SEG_BTN =
  "cursor-pointer rounded-full border-none px-[22px] py-[9px] font-display text-[0.9rem] font-normal tracking-[0.03em] transition-colors";
const CHIP =
  "inline-flex cursor-pointer items-center gap-2 rounded-full border px-3.5 py-2 text-[0.85rem] font-bold leading-[1.5] transition-colors";
</script>

<template>
  <div class="event-calendar">
    <!-- Toolbar: month nav + Month/List segmented control -->
    <section class="bg-white px-6 pt-7 md:pt-10" data-tone="white">
      <div class="mx-auto flex max-w-[1200px] flex-col gap-5">
      <div class="flex flex-col gap-4 md:flex-row md:flex-wrap md:items-center md:justify-between md:gap-5">
        <div class="flex items-center justify-between gap-2.5 md:justify-start md:gap-3.5">
          <button type="button" aria-label="Previous month" :class="NAV_BTN" @click="monthOffset--">←</button>
          <div aria-live="polite" class="text-center font-display text-[1.25rem] md:min-w-[280px] md:text-[clamp(1.3rem,2.4vw,1.8rem)]">
            {{ monthLabel }}
          </div>
          <button type="button" aria-label="Next month" :class="NAV_BTN" @click="monthOffset++">→</button>
        </div>

        <div role="group" aria-label="View" class="flex items-center gap-0.5 self-center rounded-full bg-alt p-1 md:self-auto">
          <button type="button" :aria-pressed="view === 'month'" :class="[SEG_BTN, view === 'month' ? 'bg-brand text-white' : 'bg-transparent text-ink hover:bg-control-faint']" @click="view = 'month'">
            {{ monthLabelText }}
          </button>
          <button type="button" :aria-pressed="view === 'list'" :class="[SEG_BTN, view === 'list' ? 'bg-brand text-white' : 'bg-transparent text-ink hover:bg-control-faint']" @click="view = 'list'">
            {{ listLabelText }}
          </button>
        </div>
      </div>

      <!-- Category filter chips: "All events" + one per term, swatch dot in term color -->
      <div role="group" :aria-label="filterLabelText" class="flex flex-wrap items-center gap-2">
        <span class="mr-1.5 font-display text-[0.82rem] font-bold uppercase tracking-[0.06em] text-muted">{{ filterLabelText }}</span>
        <button
          v-for="cat in EVENT_CATEGORIES"
          :key="cat.id"
          type="button"
          :aria-pressed="activeCat === cat.id"
          :class="[CHIP, activeCat === cat.id ? 'border-ink bg-ink text-white' : 'border-control bg-white text-ink hover:border-ink']"
          @click="activeCat = cat.id"
        >
          <span
            v-if="showCategoryColors && cat.color"
            aria-hidden="true"
            class="inline-block size-2.5 flex-none rounded-full"
            :style="{ backgroundColor: cat.color }"
          ></span>
          {{ cat.id === 'all' ? allEventsText : cat.label }}
        </button>
      </div>
      </div>
    </section>

    <!-- Skeleton while the window loads -->
    <section v-if="loading" class="bg-white px-4 pb-8 pt-5 min-[700px]:px-6 md:pb-14 md:pt-7" data-tone="white">
      <div aria-hidden="true" class="mx-auto max-w-[1200px] overflow-hidden rounded-[20px] shadow-gallery">
        <div class="h-11 animate-pulse bg-brand/30"></div>
        <div class="grid grid-cols-7 gap-px bg-line pt-px">
          <div v-for="n in 35" :key="`g${n}`" class="h-11 animate-pulse bg-alt min-[700px]:h-24"></div>
        </div>
      </div>
      <p role="status" class="mx-auto mt-3.5 max-w-[1200px] text-[0.9rem] font-medium text-muted">Loading events…</p>
    </section>

    <!-- Error state: the calendar feed keeps working even when the API doesn't -->
    <section v-else-if="failed" class="bg-white px-6 pb-10 pt-5 md:pb-14 md:pt-7" data-tone="white">
      <div class="mx-auto max-w-[900px]">
        <div class="flex flex-col items-center gap-1 rounded-[16px] border-2 border-dashed border-border-muted px-6 py-11 text-center md:rounded-[20px] md:px-8 md:py-16">
          <div class="text-[1.05rem] font-extrabold md:text-[1.25rem] md:font-bold">We couldn&rsquo;t load the calendar</div>
          <p class="m-0 max-w-[44ch] text-base font-medium leading-[1.45] md:text-[1.2rem]">
            Try again in a moment — or subscribe with
            <a :href="icsUrl" class="font-bold text-accent underline underline-offset-4 hover:text-brand-deep">{{ icsLabel }}</a>
            and get every event straight in your own calendar.
          </p>
          <button type="button" class="mt-4 cursor-pointer rounded-full border-2 border-accent bg-transparent px-6 py-2.5 text-[0.92rem] font-bold text-accent transition-colors hover:bg-accent hover:text-white" @click="loadEvents">
            Retry
          </button>
        </div>
      </div>
    </section>

    <template v-else>
      <!-- Month view: v4 grid (dots + legend under 700px) -->
      <section v-if="view === 'month'" class="bg-white px-4 pb-8 pt-5 min-[700px]:px-6 md:pb-14 md:pt-7" data-tone="white">
        <div class="mx-auto max-w-[1200px]">
          <MonthGrid
            :year="visibleMonth.year"
            :month="visibleMonth.month"
            :events="filtered"
            :show-category-colors="showCategoryColors"
            @select="selectedId = $event"
          />
        </div>
      </section>

      <!-- List view: EventCard rows + dashed empty month -->
      <section v-else class="bg-white px-6 pb-10 pt-5 md:pb-14 md:pt-7" data-tone="white">
        <div class="mx-auto max-w-[900px]">
          <EventListView
            :events="monthEvents"
            :view-label="viewLabel"
            :empty-title="emptyTitle"
            :empty-body="emptyBody"
          />
        </div>
      </section>
    </template>

    <EventDetailDialog
      :event="selectedEvent"
      :show-category-colors="showCategoryColors"
      :view-label="viewLabel"
      @close="selectedId = null"
    />

    <!-- Subscribe strip: Google Calendar + iCal pills -->
    <section v-if="showSubscribe" id="subscribe" class="calendar-subscribe bg-ink px-6 py-10 text-white md:py-14" data-tone="ink">
      <div class="mx-auto flex max-w-[1200px] flex-col items-start gap-4 md:flex-row md:flex-wrap md:items-center md:justify-between md:gap-8">
        <div class="flex max-w-[56ch] flex-col gap-2">
          <h2 class="m-0 font-display text-[1.2rem] font-normal md:text-[1.4rem]">{{ subscribeTitle }}</h2>
          <p class="m-0 text-[0.98rem] leading-[1.55] text-muted-on-ink md:text-[1.05rem]">{{ subscribeLede }}</p>
        </div>
        <div class="flex flex-wrap gap-2.5 md:gap-3">
          <a
            :href="googleCalUrl"
            target="_blank"
            rel="noopener"
            class="rounded-full bg-white px-6 py-[13px] font-display text-[0.9rem] font-normal tracking-[0.04em] text-ink no-underline transition-colors hover:bg-brand-deep hover:text-white md:px-[34px] md:py-3.5 md:text-base"
          >
            {{ googleLabel }}
          </a>
          <a
            :href="icsUrl"
            class="rounded-full border-2 border-white bg-transparent px-[22px] py-[11px] font-display text-[0.9rem] font-normal tracking-[0.04em] text-white no-underline transition-colors hover:bg-brand-deep hover:border-brand-deep md:px-8 md:py-3 md:text-base"
          >
            {{ icsLabel }}
          </a>
        </div>
      </div>
    </section>
  </div>
</template>
