// next-js/components/site/EventBlocks.tsx
import { BlockA11yNote } from "@/components/site/BlockA11yNote";
import { BlockAgenda } from "@/components/site/BlockAgenda";
import { BlockGoodToKnow } from "@/components/site/BlockGoodToKnow";
import { BlockMap } from "@/components/site/BlockMap";
import { BlockProse } from "@/components/site/blog/blocks/BlockProse";
import type { EventBlock } from "@/lib/schemas";

/* event_body flexible-content dispatcher (mirrors PostBlocks). Every block
 * reads the brand role tokens; `strings` supplies translated headings. */
export function EventBlocks({
  blocks,
  headings,
}: {
  blocks: EventBlock[];
  headings?: { agenda?: string; goodToKnow?: string; a11yNote?: string; map?: string };
}) {
  return (
    <>
      {blocks.map((block, i) => {
        switch (block.type) {
          case "prose":
            return <BlockProse key={i} html={block.html} />;
          case "agenda":
            return <BlockAgenda key={i} items={block.items} heading={headings?.agenda} />;
          case "good_to_know":
            return <BlockGoodToKnow key={i} items={block.items} heading={headings?.goodToKnow} />;
          case "a11y_note":
            return <BlockA11yNote key={i} html={block.html} heading={headings?.a11yNote} />;
          case "map":
            return <BlockMap key={i} address={block.address} heading={headings?.map} />;
        }
      })}
    </>
  );
}

// nuxt-js/app/components/site/EventBlocks.vue
<script setup lang="ts">
// event_body flexible-content dispatcher (mirrors PostBlocks.vue). Prose reuses
// the blog BlockProse; the rest are event-specific. v4 (openspec
// progress-now-v4-events task 3.2): every block reads the brand role tokens —
// the per-category accent color is gone.
import BlockProse from "@/components/site/blog/blocks/BlockProse.vue";
import BlockAgenda from "@/components/site/BlockAgenda.vue";
import BlockGoodToKnow from "@/components/site/BlockGoodToKnow.vue";
import BlockA11yNote from "@/components/site/BlockA11yNote.vue";
import BlockMap from "@/components/site/BlockMap.vue";
import type { EventBlock } from "@/lib/events";

defineProps<{ blocks: EventBlock[] }>();
</script>

<template>
  <template v-for="(block, i) in blocks" :key="i">
    <BlockProse v-if="block.type === 'prose'" :html="block.html" />
    <BlockAgenda v-else-if="block.type === 'agenda'" :items="block.items" />
    <BlockGoodToKnow v-else-if="block.type === 'good_to_know'" :items="block.items" />
    <BlockA11yNote v-else-if="block.type === 'a11y_note'" :html="block.html" />
    <BlockMap v-else-if="block.type === 'map'" :address="block.address" />
  </template>
</template>
